const UNI_WEBSITES = {
    "Abant İzzet Baysal Üniversitesi": "http://www.ibu.edu.tr",
    "Abdullah Gül Üniversitesi": "http://www.agu.edu.tr",
    "Acıbadem Mehmet Ali Aydınlar Üniversitesi": "https://www.acibadem.edu.tr/",
    "Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi": "https://www.atu.edu.tr",
    "Adıyaman Üniversitesi": "http://www.adiyaman.edu.tr",
    "Afyon Kocatepe Üniversitesi": "http://www.aku.edu.tr",
    "Afyonkarahisar Sağlık Bilimleri Üniversitesi": "http://afsu.edu.tr/",
    "Ağrı İbrahim Çeçen Üniversitesi": "https://www.agri.edu.tr/",
    "Ahi Evran Üniversitesi": "http://www.ahievran.edu.tr",
    "Akdeniz Üniversitesi": "http://www.akdeniz.edu.tr",
    "Aksaray Üniversitesi": "http://www.aksaray.edu.tr",
    "Alanya Alaaddin Keykubat Üniversitesi": "https://www.alanya.edu.tr/",
    "Alanya Hamdullah Emin Paşa Üniversitesi": "https://www.alanyauniversity.edu.tr/",
    "Altınbaş Üniversitesi": "https://www.altinbas.edu.tr/",
    "Amasya Üniversitesi": "http://www.amasya.edu.tr",
    "Anadolu Üniversitesi": "https://anadolu.edu.tr/",
    "Anka Teknoloji Üniversitesi": "https://veri.ulakbim.gov.tr/universite/241",
    "Ankara Bilim Üniversitesi": "https://www.ankarabilim.edu.tr/",
    "Ankara Hacı Bayram Veli Üniversitesi": "https://hacibayram.edu.tr/",
    "Ankara Medipol Üniversitesi": "http://www.ankaramedipol.edu.tr",
    "Ankara Müzik ve Güzel Sanatlar Üniversitesi": "https://www.mgu.edu.tr/",
    "Ankara Sosyal Bilimler Üniversitesi": "http://www.asbu.edu.tr/",
    "Ankara Üniversitesi": "http://www.ankara.edu.tr",
    "Ankara Yıldırım Beyazıt Üniversitesi": "http://www.aybu.edu.tr",
    "Antalya Akev Üniversitesi": "https://tr.wikipedia.org/wiki/Antalya_Belek_%C3%9Cniversitesi",
    "Antalya Bilim Üniversitesi": "https://www.antalya.edu.tr/tr",
    "Ardahan Üniversitesi": "https://ardahan.edu.tr/",
    "Artvin Çoruh Üniversitesi": "https://www.artvin.edu.tr/",
    "Ataşehir Adıgüzel Meslek Yüksekokulu": "http://www.adiguzel.edu.tr/",
    "Atatürk Üniversitesi": "http://www.atauni.edu.tr",
    "Atılım Üniversitesi": "https://www.atilim.edu.tr/",
    "Avrasya Üniversitesi": "https://www.avrasya.edu.tr",
    "Aydın Adnan Menderes Üniversitesi": "http://www.adu.edu.tr",
    "Bahçeşehir Üniversitesi": "http://www.bahcesehir.edu.tr",
    "Balıkesir Üniversitesi": "https://www.balikesir.edu.tr/",
    "Bandırma Onyedi Eylül Üniversitesi": "https://www.bandirma.edu.tr/",
    "Bartın Üniversitesi": "http://www.bartin.edu.tr",
    "Başkent Üniversitesi": "http://baskent.edu.tr",
    "Batman Üniversitesi": "http://www.batman.edu.tr",
    "Bayburt Üniversitesi": "http://www.bayburt.edu.tr",
    "Beykent Üniversitesi": "http://www.beykent.edu.tr",
    "Beykoz Üniversitesi": "https://www.beykoz.edu.tr/",
    "Bezmialem Vakıf Üniversitesi": "http://www.bezmialem.edu.tr",
    "Bilecik Şeyh Edebali Üniversitesi": "http://www.bilecik.edu.tr",
    "Bingöl Üniversitesi": "http://www.bingol.edu.tr",
    "Biruni Üniversitesi": "https://www.biruni.edu.tr/",
    "Bitlis Eren Üniversitesi": "https://www.beu.edu.tr",
    "Boğaziçi Üniversitesi": "https://bogazici.edu.tr/",
    "Bolu Abant İzzet Baysal Üniversitesi": "http://www.ibu.edu.tr",
    "Burdur Mehmet Akif Ersoy Üniversitesi": "http://www.mehmetakif.edu.tr",
    "Bursa Teknik Üniversitesi": "http://www.btu.edu.tr/",
    "Bursa Uludağ Üniversitesi": "http://uludag.edu.tr",
    "Çağ Üniversitesi": "http://www.cag.edu.tr",
    "Çanakkale Onsekiz Mart Üniversitesi": "http://www.comu.edu.tr",
    "Çankaya Üniversitesi": "http://www.cankaya.edu.tr",
    "Çankırı Karatekin Üniversitesi": "https://www.karatekin.edu.tr/",
    "Çukurova Üniversitesi": "http://www.cu.edu.tr",
    "Demiroğlu Bilim Üniversitesi": "http://demiroglu.bilim.edu.tr",
    "Dicle Üniversitesi": "http://www.dicle.edu.tr",
    "Doğuş Üniversitesi": "http://www.dogus.edu.tr",
    "Dokuz Eylül Üniversitesi": "http://www.deu.edu.tr",
    "Düzce Üniversitesi": "http://www.duzce.edu.tr",
    "Ege Üniversitesi": "http://www.ege.edu.tr",
    "Erciyes Üniversitesi": "http://www.erciyes.edu.tr",
    "Erzincan Binali Yıldırım Üniversitesi": "http://www.ebyu.edu.tr",
    "Erzurum Teknik Üniversitesi": "http://www.erzurum.edu.tr/",
    "Eskişehir Osmangazi Üniversitesi": "https://www.ogu.edu.tr/",
    "Eskişehir Teknik Üniversitesi": "https://www.eskisehir.edu.tr/",
    "Fatih Sultan Mehmet Vakıf Üniversitesi": "https://www.fsm.edu.tr/",
    "Fenerbahçe Üniversitesi": "http://fbu.edu.tr",
    "Fırat Üniversitesi": "http://www.firat.edu.tr",
    "Galatasaray Üniversitesi": "https://gsu.edu.tr/",
    "Gazi Üniversitesi": "https://gazi.edu.tr/",
    "Gaziantep İslam Bilim ve Teknoloji Üniversitesi": "http://www.gibtu.edu.tr/",
    "Gaziantep Üniversitesi": "http://www.gantep.edu.tr",
    "Gebze Teknik Üniversitesi": "http://www.gtu.edu.tr/",
    "Giresun Üniversitesi": "http://www.giresun.edu.tr",
    "Gümüşhane Üniversitesi": "http://www.gumushane.edu.tr/",
    "Hacettepe Üniversitesi": "http://www.hacettepe.edu.tr/",
    "Hakkari Üniversitesi": "http://www.hakkari.edu.tr",
    "Haliç Üniversitesi": "http://www.halic.edu.tr/",
    "Harran Üniversitesi": "http://www.harran.edu.tr",
    "Hasan Kalyoncu Üniversitesi": "https://www.hku.edu.tr/",
    "Hatay Mustafa Kemal Üniversitesi": "http://www.mku.edu.tr",
    "Hitit Üniversitesi": "http://www.hitit.edu.tr",
    "Iğdır Üniversitesi": "http://www.igdir.edu.tr",
    "Isparta Uygulamalı Bilimler Üniversitesi": "https://isparta.edu.tr/",
    "Işık Üniversitesi": "http://www.isikun.edu.tr",
    "İbn Haldun Üniversitesi": "https://www.ihu.edu.tr/tr",
    "İhsan Doğramacı Bilkent Üniversitesi": "http://www.bilkent.edu.tr",
    "İnönü Üniversitesi": "http://inonu.edu.tr",
    "İskenderun Teknik Üniversitesi": "https://iste.edu.tr/",
    "İstanbul 29 Mayıs Üniversitesi": "https://www.29mayis.edu.tr/",
    "İstanbul Arel Üniversitesi": "http://www.arel.edu.tr",
    "İstanbul Atlas Üniversitesi": "http://www.atlas.edu.tr/",
    "İstanbul Aydın Üniversitesi": "http://www.aydin.edu.tr",
    "İstanbul Ayvansaray Üniversitesi": "https://tr.wikipedia.org/wiki/%C4%B0stanbul_Topkap%C4%B1_%C3%9Cniversitesi",
    "İstanbul Bilgi Üniversitesi": "https://www.bilgi.edu.tr/tr/",
    "İstanbul Bilim Üniversitesi": "http://demiroglu.bilim.edu.tr",
    "İstanbul Esenyurt Üniversitesi": "http://esenyurt.edu.tr/",
    "İstanbul Galata Üniversitesi": "https://www.galata.edu.tr/",
    "İstanbul Gedik Üniversitesi": "http://www.gedik.edu.tr",
    "İstanbul Gelişim Üniversitesi": "http://www.gelisim.edu.tr/",
    "İstanbul Kent Üniversitesi": "http://www.kent.edu.tr/",
    "İstanbul Kültür Üniversitesi": "https://www.iku.edu.tr/",
    "İstanbul Medeniyet Üniversitesi": "https://www.medeniyet.edu.tr/",
    "İstanbul Medipol Üniversitesi": "http://www.medipol.edu.tr/",
    "İstanbul Okan Üniversitesi": "http://www.okan.edu.tr",
    "İstanbul Rumeli Üniversitesi": "https://rumeli.edu.tr/",
    "İstanbul Sabahattin Zaim Üniversitesi": "https://www.izu.edu.tr/",
    "İstanbul Sağlık ve Sosyal Bilimler Meslek Yüksekokulu": "http://www.issb.edu.tr/",
    "İstanbul Sağlık ve Teknoloji Üniversitesi": "https://www.istun.edu.tr/",
    "İstanbul Şişli Meslek Yüksekokulu": "http://www.sisli.edu.tr/",
    "İstanbul Teknik Üniversitesi": "http://www.itu.edu.tr/",
    "İstanbul Ticaret Üniversitesi": "https://ticaret.edu.tr/",
    "İstanbul Topkapı Üniversitesi": "https://www.topkapi.edu.tr/",
    "İstanbul Üniversitesi": "http://www.istanbul.edu.tr",
    "İstanbul Üniversitesi-Cerrahpaşa": "https://www.iuc.edu.tr/",
    "İstanbul Yeni Yüzyıl Üniversitesi": "http://www.yeniyuzyil.edu.tr",
    "İstinye Üniversitesi": "https://www.istinye.edu.tr/tr",
    "İzmir Bakırçay Üniversitesi": "https://www.bakircay.edu.tr",
    "İzmir Demokrasi Üniversitesi": "http://www.idu.edu.tr",
    "İzmir Ekonomi Üniversitesi": "https://www.ieu.edu.tr/tr",
    "İzmir Katip Çelebi Üniversitesi": "http://www.ikc.edu.tr",
    "İzmir Kavram Meslek Yüksekokulu": "https://tr.wikipedia.org/wiki/%C4%B0zmir_Kavram_Meslek_Y%C3%BCksekokulu",
    "İzmir Tınaztepe Üniversitesi": "https://www.tinaztepe.edu.tr",
    "İzmir Yüksek Teknoloji Enstitüsü": "https://www.teknoparkizmir.com.tr/",
    "Kadir Has Üniversitesi": "http://www.khas.edu.tr/",
    "Kafkas Üniversitesi": "https://www.kafkas.edu.tr/",
    "Kahramanmaraş İstiklal Üniversitesi": "https://www.istiklal.edu.tr/",
    "Kahramanmaraş Sütçü İmam Üniversitesi": "https://www.ksu.edu.tr/",
    "Karabük Üniversitesi": "http://www.karabuk.edu.tr",
    "Karadeniz Teknik Üniversitesi": "http://www.ktu.edu.tr/",
    "Karamanoğlu Mehmetbey Üniversitesi": "http://www.kmu.edu.tr/",
    "Kastamonu Üniversitesi": "http://www.kastamonu.edu.tr",
    "Kayseri Üniversitesi": "https://www.kayseri.edu.tr/",
    "Kıbrıs İlim Üniversitesi": "https://cau.edu.tr/",
    "Kırıkkale Üniversitesi": "http://www.kku.edu.tr",
    "Kırklareli Üniversitesi": "http://www.kirklareli.edu.tr",
    "Kırşehir Ahi Evran Üniversitesi": "http://www.ahievran.edu.tr",
    "Kilis 7 Aralık Üniversitesi": "http://www.kilis.edu.tr",
    "Kocaeli Sağlık ve Teknoloji Üniversitesi": "https://kocaelisaglik.edu.tr/",
    "Kocaeli Üniversitesi": "https://www.kocaeli.edu.tr/",
    "Koç Üniversitesi": "https://www.ku.edu.tr/",
    "Konya Gıda ve Tarım Üniversitesi": "http://www.gidatarim.edu.tr/",
    "Konya Teknik Üniversitesi": "https://www.ktun.edu.tr/",
    "KTO Karatay Üniversitesi": "https://www.karatay.edu.tr/tr/",
    "Kütahya Dumlupınar Üniversitesi": "http://www.dpu.edu.tr",
    "Kütahya Sağlık Bilimleri Üniversitesi": "https://ksbu.edu.tr/",
    "Lokman Hekim Üniversitesi": "https://www.lokmanhekim.edu.tr/",
    "Malatya Turgut Özal Üniversitesi": "https://www.ozal.edu.tr/",
    "Maltepe Üniversitesi": "http://www.maltepe.edu.tr/",
    "Manisa Celal Bayar Üniversitesi": "http://www.mcbu.edu.tr/",
    "Mardin Artuklu Üniversitesi": "https://www.artuklu.edu.tr/",
    "Marmara Üniversitesi": "http://www.marmara.edu.tr",
    "MEF Üniversitesi": "https://www.mef.edu.tr/",
    "Mersin Üniversitesi": "http://www.mersin.edu.tr/",
    "Mimar Sinan Güzel Sanatlar Üniversitesi": "https://www.msgsu.edu.tr/",
    "Mudanya Üniversitesi": "https://mudanya.edu.tr/",
    "Muğla Sıtkı Koçman Üniversitesi": "http://mu.edu.tr",
    "Munzur Üniversitesi": "https://www.munzur.edu.tr/",
    "Muş Alparslan Üniversitesi": "https://www.alparslan.edu.tr/",
    "Necmettin Erbakan Üniversitesi": "https://erbakan.edu.tr/",
    "Nevşehir Hacı Bektaş Veli Üniversitesi": "https://www.nevsehir.edu.tr/",
    "Niğde Ömer Halisdemir Üniversitesi": "https://www.ohu.edu.tr/",
    "Nişantaşı Üniversitesi": "https://www.nisantasi.edu.tr/",
    "Nuh Naci Yazgan Üniversitesi": "https://www.nny.edu.tr/",
    "Ondokuz Mayıs Üniversitesi": "https://www.omu.edu.tr/",
    "Ordu Üniversitesi": "https://www.odu.edu.tr/",
    "Orta Doğu Teknik Üniversitesi (ODTÜ)": "https://www.metu.edu.tr/tr",
    "Osmaniye Korkut Ata Üniversitesi": "http://www.oku.edu.tr",
    "Ostim Teknik Üniversitesi": "https://www.ostimteknik.edu.tr/",
    "Özyeğin Üniversitesi": "http://www.ozyegin.edu.tr/",
    "Pamukkale Üniversitesi": "http://pau.edu.tr/",
    "Piri Reis Üniversitesi": "https://pirireis.edu.tr/",
    "Recep Tayyip Erdoğan Üniversitesi": "https://www.erdogan.edu.tr/",
    "Sabancı Üniversitesi": "http://www.sabanciuniv.edu",
    "Sağlık Bilimleri Üniversitesi": "https://www.sbu.edu.tr/",
    "Sakarya Uygulamalı Bilimler Üniversitesi": "http://www.subu.edu.tr/tr",
    "Sakarya Üniversitesi": "https://www.sakarya.edu.tr/",
    "Samsun Üniversitesi": "http://samsun.edu.tr",
    "Sanko Üniversitesi": "http://www.sanko.edu.tr/",
    "Selçuk Üniversitesi": "http://www.selcuk.edu.tr",
    "Siirt Üniversitesi": "https://siirt.edu.tr/",
    "Sinop Üniversitesi": "http://www.sinop.edu.tr",
    "Sivas Bilim ve Teknoloji Üniversitesi": "https://www.sivas.edu.tr",
    "Sivas Cumhuriyet Üniversitesi": "http://www.cumhuriyet.edu.tr",
    "Süleyman Demirel Üniversitesi": "https://w3.sdu.edu.tr/",
    "Şırnak Üniversitesi": "http://www.sirnak.edu.tr/",
    "Tarsus Üniversitesi": "http://www.tarsus.edu.tr",
    "TED Üniversitesi": "http://www.tedu.edu.tr/",
    "Tekirdağ Namık Kemal Üniversitesi": "http://www.nku.edu.tr",
    "TOBB Ekonomi ve Teknoloji Üniversitesi": "http://www.etu.edu.tr",
    "Tokat Gaziosmanpaşa Üniversitesi": "http://www.gop.edu.tr",
    "Toros Üniversitesi": "http://www.toros.edu.tr",
    "Trabzon Üniversitesi": "https://www.trabzon.edu.tr/",
    "Trakya Üniversitesi": "http://www.trakya.edu.tr",
    "Türk Hava Kurumu Üniversitesi": "https://www.thk.edu.tr/",
    "Türk-Alman Üniversitesi": "http://www.tau.edu.tr/",
    "Türk-Japon Bilim ve Teknoloji Üniversitesi": "https://tju.edu.tr/",
    "Ufuk Üniversitesi": "https://www.ufuk.edu.tr/",
    "Uşak Üniversitesi": "https://www.usak.edu.tr/",
    "Üsküdar Üniversitesi": "http://www.uskudar.edu.tr/",
    "Van Yüzüncü Yıl Üniversitesi": "http://www.yyu.edu.tr",
    "Yalova Üniversitesi": "http://www.yalova.edu.tr",
    "Yaşar Üniversitesi": "https://www.yasar.edu.tr/",
    "Yeditepe Üniversitesi": "https://yeditepe.edu.tr/tr",
    "Yıldız Teknik Üniversitesi (YTÜ)": "https://www.yildiz.edu.tr/",
    "Yozgat Bozok Üniversitesi": "http://www.bozok.edu.tr",
    "Yüksek İhtisas Üniversitesi": "https://www.yuksekihtisasuniversitesi.edu.tr/",
    "Zonguldak Bülent Ecevit Üniversitesi": "http://www.beun.edu.tr"
};
