const UNI_IMAGES = {
    "Abant İzzet Baysal Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/5/54/BA%C4%B0B%C3%9C_logo.png",
    "Abdullah Gül Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Abdullah_G%C3%BCl_University_logo.svg/1280px-Abdullah_G%C3%BCl_University_logo.svg.png",
    "Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/4/48/ATU_logo.png",
    "Adıyaman Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Ad%C4%B1yaman_University_logo.svg/1280px-Ad%C4%B1yaman_University_logo.svg.png",
    "Ahi Evran Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/K%C4%B1r%C5%9Fehir_Ahi_Evran_University_logo.svg/1280px-K%C4%B1r%C5%9Fehir_Ahi_Evran_University_logo.svg.png",
    "Altınbaş Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Coat_of_Arms_of_Alt%C4%B1nba%C5%9F_University.svg/1280px-Coat_of_Arms_of_Alt%C4%B1nba%C5%9F_University.svg.png",
    "Amasya Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Amasya_University_logo.svg/1280px-Amasya_University_logo.svg.png",
    "Anadolu Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Anadolu_University%2C_Eski%C5%9Fehir.jpg/1280px-Anadolu_University%2C_Eski%C5%9Fehir.jpg",
    "Anka Teknoloji Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Kundura.jpg/1280px-Kundura.jpg",
    "Ankara Bilim Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/b/b6/Ankara_Bilim_%C3%9Cniversitesi_Kurumsal_Logo.png",
    "Ankara Hacı Bayram Veli Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Ankara_Hac%C4%B1_Bayram_Veli_University_logo_%28vertical_tr%29.svg/1280px-Ankara_Hac%C4%B1_Bayram_Veli_University_logo_%28vertical_tr%29.svg.png",
    "Ankara Medipol Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Ankara_tren_ist1.JPG/1280px-Ankara_tren_ist1.JPG",
    "Ankara Sosyal Bilimler Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/9/9f/Ankara_Sosyal_Bilimler_Yaz%C4%B1.jpg",
    "Ankara Yıldırım Beyazıt Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Ankara_Y%C4%B1ld%C4%B1r%C4%B1m_Beyaz%C4%B1t_University_logo.svg/1280px-Ankara_Y%C4%B1ld%C4%B1r%C4%B1m_Beyaz%C4%B1t_University_logo.svg.png",
    "Antalya Bilim Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Antalya_Bilim_%C3%9Cniversitesi_logo.svg/1280px-Antalya_Bilim_%C3%9Cniversitesi_logo.svg.png",
    "Artvin Çoruh Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Artvin_%C3%87oruh_University_logo.svg/1280px-Artvin_%C3%87oruh_University_logo.svg.png",
    "Ataşehir Adıgüzel Meslek Yüksekokulu": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Ata%C5%9Fehir_Ad%C4%B1g%C3%BCzel_Meslek_Y%C3%BCksekokulu_logo.svg/1280px-Ata%C5%9Fehir_Ad%C4%B1g%C3%BCzel_Meslek_Y%C3%BCksekokulu_logo.svg.png",
    "Atılım Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/At%C4%B1l%C4%B1m_%C3%9Cniversitesi_logo.svg/1280px-At%C4%B1l%C4%B1m_%C3%9Cniversitesi_logo.svg.png",
    "Aydın Adnan Menderes Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Ayd%C4%B1n_Adnan_Menderes_University_logo.svg/1280px-Ayd%C4%B1n_Adnan_Menderes_University_logo.svg.png",
    "Bahçeşehir Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Bahcesehir_university_in_Istanbul_-_panoramio.jpg/1280px-Bahcesehir_university_in_Istanbul_-_panoramio.jpg",
    "Başkent Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Ba%C5%9Fkent_%C3%9Cniversitesi_logo.svg/1280px-Ba%C5%9Fkent_%C3%9Cniversitesi_logo.svg.png",
    "Bayburt Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Bayburt_University_logo.svg/1280px-Bayburt_University_logo.svg.png",
    "Biruni Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Biruni_%C3%9Cniversitesi_logo.svg/1280px-Biruni_%C3%9Cniversitesi_logo.svg.png",
    "Boğaziçi Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/d/d9/Bogazici_University.jpg",
    "Bolu Abant İzzet Baysal Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/5/54/BA%C4%B0B%C3%9C_logo.png",
    "Burdur Mehmet Akif Ersoy Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Mehmet_Akif_Ersoy_University.jpg/1280px-Mehmet_Akif_Ersoy_University.jpg",
    "Bursa Uludağ Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Bursa_Uluda%C4%9F_University_logo.svg/1280px-Bursa_Uluda%C4%9F_University_logo.svg.png",
    "Çanakkale Onsekiz Mart Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/%C3%87anakkale_Onsekiz_Mart_University_%281%29.jpg/1280px-%C3%87anakkale_Onsekiz_Mart_University_%281%29.jpg",
    "Çankaya Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/A_view_of_the_%C3%87ankaya_University_new_campus.jpg/1280px-A_view_of_the_%C3%87ankaya_University_new_campus.jpg",
    "Çankırı Karatekin Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/%C3%87ank%C4%B1r%C4%B1_Karatekin_University_logo.svg/1280px-%C3%87ank%C4%B1r%C4%B1_Karatekin_University_logo.svg.png",
    "Çukurova Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/%C3%87ukurova_University_logo.svg/1280px-%C3%87ukurova_University_logo.svg.png",
    "Doğuş Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/e/eb/Dogus_universitesi_yeni_logo.png",
    "Düzce Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/D%C3%BCzce_University_logo.svg/1280px-D%C3%BCzce_University_logo.svg.png",
    "Ege Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Ege_University_logo.svg/1280px-Ege_University_logo.svg.png",
    "Erciyes Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Erciyes_University_logo.svg/1280px-Erciyes_University_logo.svg.png",
    "Erzincan Binali Yıldırım Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/3/39/Erzincanuni.jpg",
    "Erzurum Teknik Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Erzurum_Technical_University_logo.svg/1280px-Erzurum_Technical_University_logo.svg.png",
    "Eskişehir Teknik Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Eski%C5%9Fehir_Technical_University_logo.svg/1280px-Eski%C5%9Fehir_Technical_University_logo.svg.png",
    "Fatih Sultan Mehmet Vakıf Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Fatih_Sultan_Mehmet_University_logo.svg/1280px-Fatih_Sultan_Mehmet_University_logo.svg.png",
    "Fenerbahçe Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Fenerbah%C3%A7e_%C3%9Cniversitesi_Binas%C4%B1.jpg/1280px-Fenerbah%C3%A7e_%C3%9Cniversitesi_Binas%C4%B1.jpg",
    "Fırat Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/F%C4%B1rat_University_logo.svg/1280px-F%C4%B1rat_University_logo.svg.png",
    "Galatasaray Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/c/c4/Galatasaray_%C3%9Cniversitesi.jpg",
    "Hacettepe Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Montage_of_Hacettepe_University_Beytepe_Campus.png/1280px-Montage_of_Hacettepe_University_Beytepe_Campus.png",
    "Hitit Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Hitit_University_logo.svg/1280px-Hitit_University_logo.svg.png",
    "Iğdır Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/I%C4%9Fd%C4%B1r_University_logo.svg/1280px-I%C4%9Fd%C4%B1r_University_logo.svg.png",
    "Işık Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/I%C5%9F%C4%B1k_5869.jpg/1280px-I%C5%9F%C4%B1k_5869.jpg",
    "İstanbul Arel Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/%C4%B0stanbul_Arel_University_logo.svg/1280px-%C4%B0stanbul_Arel_University_logo.svg.png",
    "İstanbul Aydın Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Istanbul_Ayd%C4%B1n_University_logo.svg/1280px-Istanbul_Ayd%C4%B1n_University_logo.svg.png",
    "İstanbul Kültür Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Atakoy1.jpg/1280px-Atakoy1.jpg",
    "İstanbul Medeniyet Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/%C4%B0stanbul_Medeniyet_%C3%9Cniversitesi_logo.svg/1280px-%C4%B0stanbul_Medeniyet_%C3%9Cniversitesi_logo.svg.png",
    "İstanbul Sabahattin Zaim Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/d/dd/Izulogoyuvarlak.png",
    "İstanbul Sağlık ve Teknoloji Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/%C4%B0ST%C3%9CN1IMG_0065.jpg/1280px-%C4%B0ST%C3%9CN1IMG_0065.jpg",
    "İstanbul Teknik Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Istanbul_asv2020-02_img69_Ma%C3%A7ka_Armory.jpg/1280px-Istanbul_asv2020-02_img69_Ma%C3%A7ka_Armory.jpg",
    "İstanbul Topkapı Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/%C4%B0stanbul_Topkap%C4%B1_%C3%9Cniversitesi_logo.svg/1280px-%C4%B0stanbul_Topkap%C4%B1_%C3%9Cniversitesi_logo.svg.png",
    "İstanbul Üniversitesi-Cerrahpaşa": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/%C4%B0stanbul_%C3%9Cniversitesi-Cerrahpa%C5%9Fa_logo.svg/1280px-%C4%B0stanbul_%C3%9Cniversitesi-Cerrahpa%C5%9Fa_logo.svg.png",
    "İzmir Bakırçay Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Bak%C4%B1r%C3%A7ay_%C3%9Cniversitesi_logo.svg/1280px-Bak%C4%B1r%C3%A7ay_%C3%9Cniversitesi_logo.svg.png",
    "İzmir Demokrasi Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/%C4%B0zmir_Democracy_University%2C_March_2019.jpg/1280px-%C4%B0zmir_Democracy_University%2C_March_2019.jpg",
    "İzmir Ekonomi Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/4/4f/Ieu-logo-kullaim-2.png",
    "Kadir Has Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Kadir_Has_%C3%9Cniversitesi_Mart_2013.JPG/1280px-Kadir_Has_%C3%9Cniversitesi_Mart_2013.JPG",
    "Kırşehir Ahi Evran Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/K%C4%B1r%C5%9Fehir_Ahi_Evran_University_logo.svg/1280px-K%C4%B1r%C5%9Fehir_Ahi_Evran_University_logo.svg.png",
    "Konya Gıda ve Tarım Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/0/02/KGTU-Logo.jpg",
    "KTO Karatay Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/KtoLOGO.png/1280px-KtoLOGO.png",
    "Mimar Sinan Güzel Sanatlar Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Mimar_Sinan_Fine_Arts_University.jpg/1280px-Mimar_Sinan_Fine_Arts_University.jpg",
    "Ordu Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Ordu_University_logo.svg/1280px-Ordu_University_logo.svg.png",
    "Tekirdağ Namık Kemal Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Tekirda%C4%9F_Nam%C4%B1k_Kemal_University_logo.svg/1280px-Tekirda%C4%9F_Nam%C4%B1k_Kemal_University_logo.svg.png",
    "Türk-Japon Bilim ve Teknoloji Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Turkish-Japanese_Science_And_Technology_University_logo.svg/1280px-Turkish-Japanese_Science_And_Technology_University_logo.svg.png",
    "Yaşar Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Ya%C5%9Far_%C3%9Cniversitesi.jpg/1280px-Ya%C5%9Far_%C3%9Cniversitesi.jpg",
    "Yıldız Teknik Üniversitesi (YTÜ)": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Y%C4%B1ld%C4%B1z_Technical_University_logo.svg/1280px-Y%C4%B1ld%C4%B1z_Technical_University_logo.svg.png",
    "Acıbadem Mehmet Ali Aydınlar Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/2/2a/AcibademUniLogoOrjinal.png",
    "Afyon Kocatepe Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/4/4c/Afyon_Kocatepe_%C3%9Cniversitesi_logo.png",
    "Afyonkarahisar Sağlık Bilimleri Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/e/e3/Afyonkarahisar_Sa%C4%9Fl%C4%B1k_Bilimleri_%C3%9Cniversitesi_logo.png",
    "Ağrı İbrahim Çeçen Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/b/be/A%C4%9Fr%C4%B1%C4%B0brahim%C3%87e%C3%A7en%C3%9Cniversitesi-logo.png",
    "Akdeniz Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/d/dc/Akdeniz_%C3%9Cniversitesi_logosu.IMG_0838.png",
    "Aksaray Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/3/3b/Aksaray_%C3%9Cniversitesi_logo.jpg",
    "Alanya Alaaddin Keykubat Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/2/2e/Alkulogo.png",
    "Alanya Hamdullah Emin Paşa Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/0/00/Alanya_%C3%9Cniversitesi_logo.png",
    "Ankara Müzik ve Güzel Sanatlar Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/3/33/Ankara_M%C3%BCzik_ve_G%C3%BCzel_Sanatlar_%C3%9Cniversitesi_logosu.png",
    "Ankara Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/5/5f/Ankara_%C3%9Cniversitesi_logosu.png",
    "Antalya Akev Üniversitesi": "https://ui-avatars.com/api/?name=Antalya+Akev+%C3%9Cniversitesi&background=random",
    "Ardahan Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/3/3b/Ardahan_%C3%9Cniversitesi_logosu.png",
    "Atatürk Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/c/cc/Ataturkuni_logo.png",
    "Avrasya Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/e/ee/Avrasya_%C3%9Cniversitesi.png",
    "Balıkesir Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/6/69/Bal%C4%B1kesir_%C3%9Cniversitesi_logo.png",
    "Bandırma Onyedi Eylül Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/0/0c/Bandirma-onyedi-eylul-logo.jpg",
    "Bartın Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/7/7b/Bart%C4%B1n_%C3%9Cniversitesi_logosu.jpg",
    "Batman Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/d/d8/Batman_%C3%9Cniversitesi_logosu.jpg",
    "Beykent Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/7/7e/Beykent_Universitesi_Logo_Yeni.png",
    "Beykoz Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/2/27/Beykoz_University_logo.svg",
    "Bezmialem Vakıf Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/2/21/Bezmi%C3%A2lem_Vak%C4%B1f_%C3%9Cniversitesi_logosu.png",
    "Bilecik Şeyh Edebali Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/7/73/Bilecik_%C5%9Eeyh_Edebali_%C3%9Cniversitesi_logosu.jpg",
    "Bingöl Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/9/9d/Bing%C3%B6l_%C3%9Cniversitesi_Logo.png",
    "Bitlis Eren Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/9/9c/Bitlis_Eren_%C3%9Cniversitesi_logosu.jpg",
    "Bursa Teknik Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/0/04/Bursa_Teknik_%C3%9Cniversitesi_Logosu.png",
    "Çağ Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/9/9b/Cag_universitesi.png",
    "Demiroğlu Bilim Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/1/18/Demiro%C4%9Flu_Bilim_%C3%9Cniversitesi_logo.png",
    "Dicle Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/c/c8/Dicle_%C3%9Cniversitesi_eski_logo.png",
    "Dokuz Eylül Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/1/1e/Deu_logo.png",
    "Eskişehir Osmangazi Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/6/6d/Esogu_logo.png",
    "Gazi Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/4/4e/Gazi_%C3%9Cniversitesi_logo.png",
    "Gaziantep İslam Bilim ve Teknoloji Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/5/5d/G%C4%B0BT%C3%9C_logo.png",
    "Gaziantep Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Gaziantep_University_logo.svg/1280px-Gaziantep_University_logo.svg.png",
    "Gebze Teknik Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/2/23/Gebze_Teknik_%C3%9Cniversitesi.PNG",
    "Giresun Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/a/ab/Giresun_%C3%9Cniversitesi_Logosu.png",
    "Gümüşhane Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/G%C3%BCm%C3%BC%C5%9Fhane_University_logo.svg/1280px-G%C3%BCm%C3%BC%C5%9Fhane_University_logo.svg.png",
    "Hakkari Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Hakkari_University_logo.svg/1280px-Hakkari_University_logo.svg.png",
    "Haliç Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Hali%C3%A7_University_logo_%282022%29.svg/1280px-Hali%C3%A7_University_logo_%282022%29.svg.png",
    "Harran Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/2/22/Harran_%C3%9Cniversitesi_logo.png",
    "Hasan Kalyoncu Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/e/e6/Hasan_Kalyoncu_%C3%9Cniversitesi_logosu.png",
    "Hatay Mustafa Kemal Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/1/17/Hmku_logo.png",
    "Isparta Uygulamalı Bilimler Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/2/28/ISUB%C3%9C_logo.png",
    "İbn Haldun Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/%C4%B0bn_Haldun_%C3%9Cniversitesi_logo.svg/1280px-%C4%B0bn_Haldun_%C3%9Cniversitesi_logo.svg.png",
    "İhsan Doğramacı Bilkent Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/e/ee/Bilkent%C3%9Cniversitesi-logo.png",
    "İnönü Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/%C4%B0n%C3%B6n%C3%BC_University_logo.svg/1280px-%C4%B0n%C3%B6n%C3%BC_University_logo.svg.png",
    "İskenderun Teknik Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/3/38/%C4%B0skenderun_Teknik_%C3%9Cniversitesi.png",
    "İstanbul 29 Mayıs Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/%C4%B0stanbul_29_May%C4%B1s_%C3%9Cniversitesi_logo.svg/1280px-%C4%B0stanbul_29_May%C4%B1s_%C3%9Cniversitesi_logo.svg.png",
    "İstanbul Atlas Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Atlas_University_logo.svg/1280px-Atlas_University_logo.svg.png",
    "İstanbul Ayvansaray Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/%C4%B0stanbul_Topkap%C4%B1_%C3%9Cniversitesi_logo.svg/1280px-%C4%B0stanbul_Topkap%C4%B1_%C3%9Cniversitesi_logo.svg.png",
    "İstanbul Bilgi Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/7/71/%C4%B0stanbul_Bilgi_%C3%9Cniversitesi_logo.svg",
    "İstanbul Bilim Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/1/18/Demiro%C4%9Flu_Bilim_%C3%9Cniversitesi_logo.png",
    "İstanbul Esenyurt Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/0/00/%C4%B0stanbul_esenyurt_universitesi.png",
    "İstanbul Galata Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/4/42/%C4%B0stanbul_Galata_%C3%9Cniversitesi_logo.png",
    "İstanbul Gedik Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/thumb/9/95/%C4%B0stanbul-Gedik-%C3%9Cniversitesi-Yeni-Logo.png/1280px-%C4%B0stanbul-Gedik-%C3%9Cniversitesi-Yeni-Logo.png",
    "İstanbul Gelişim Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/3/3e/%C4%B0stanbul_Geli%C5%9Fim_%C3%9Cniversitesi_logo%2C_2022.png",
    "İstanbul Kent Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/a/a9/%C4%B0stanbul_Kent_%C3%9Cniversitesi_logo.png",
    "İstanbul Medipol Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/f/f6/%C4%B0stanbul_Medipol_%C3%9Cniversitesi_Vikipedi_%C3%96%C4%9Frenci_Kul%C3%BCb%C3%BC_logo.svg",
    "İstanbul Okan Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/3/3d/Okan_%C3%9Cniversitesi_logo.png",
    "İstanbul Rumeli Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/1/10/%C4%B0stanbul_Rumeli_%C3%9Cniversitesi_logo.png",
    "İstanbul Sağlık ve Sosyal Bilimler Meslek Yüksekokulu": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/FARUK_SARA%C3%87_MESLEK_Y%C3%9CKSEK_OKULU_-_panoramio.jpg/1280px-FARUK_SARA%C3%87_MESLEK_Y%C3%9CKSEK_OKULU_-_panoramio.jpg",
    "İstanbul Şişli Meslek Yüksekokulu": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/%C4%B0stanbul_%C5%9Ei%C5%9Fli_Meslek_Y%C3%BCksekokulu_logo.svg/1280px-%C4%B0stanbul_%C5%9Ei%C5%9Fli_Meslek_Y%C3%BCksekokulu_logo.svg.png",
    "İstanbul Ticaret Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/4/44/%C4%B0stanbul_Ticaret_%C3%9Cniversitesi_Logo.png",
    "İstanbul Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/%C4%B0stanbul_%C3%9Cniversitesi_Logo.svg/1280px-%C4%B0stanbul_%C3%9Cniversitesi_Logo.svg.png",
    "İstanbul Yeni Yüzyıl Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/f/ff/Yeni_Y%C3%BCzy%C4%B1l_%C3%9Cniversitesi_logo.png",
    "İstinye Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/d/d9/%C4%B0stinye_%C3%9Cniversitesi_logo.svg",
    "İzmir Katip Çelebi Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/%C4%B0zmir_Katip_%C3%87elebi_%C3%9Cniversitesi_Giri%C5%9F_ve_%C3%87%C4%B1k%C4%B1%C5%9F_Kap%C4%B1s%C4%B1.jpg/1280px-%C4%B0zmir_Katip_%C3%87elebi_%C3%9Cniversitesi_Giri%C5%9F_ve_%C3%87%C4%B1k%C4%B1%C5%9F_Kap%C4%B1s%C4%B1.jpg",
    "İzmir Kavram Meslek Yüksekokulu": "https://upload.wikimedia.org/wikipedia/tr/d/d1/%C4%B0zmir_Kavram_MYO_logo.png",
    "İzmir Tınaztepe Üniversitesi": "https://ui-avatars.com/api/?name=%C4%B0zmir+T%C4%B1naztepe+%C3%9Cniversitesi&background=random",
    "İzmir Yüksek Teknoloji Enstitüsü": "https://upload.wikimedia.org/wikipedia/tr/b/bd/%C4%B0yte_t%C3%BCrk%C3%A7e_logo.png",
    "Kafkas Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/5/50/Kafkas_%C3%9Cniversitesi_logosu.jpg",
    "Kahramanmaraş İstiklal Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/7/73/D%C4%B1%C5%9F_%C3%A7ekim.jpg",
    "Kahramanmaraş Sütçü İmam Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/thumb/6/6f/Kahramanmara%C5%9F-S%C3%BCt%C3%A7%C3%BC-%C4%B0mam-%C3%9Cniversitesi-logo.svg/1280px-Kahramanmara%C5%9F-S%C3%BCt%C3%A7%C3%BC-%C4%B0mam-%C3%9Cniversitesi-logo.svg.png",
    "Karabük Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/2/2c/Karab%C3%BCk_%C3%9Cniversitesi_logosu.png",
    "Karadeniz Teknik Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/1/13/Blackseatechnical_university.png",
    "Karamanoğlu Mehmetbey Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/1/13/Karamano%C4%9Flu_Mehmetbey_%C3%9Cniversitesi_logosu.jpg",
    "Kastamonu Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/3/37/Kastamonu_%C3%9Cniversitesi_logosu.jpg",
    "Kayseri Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/c/c3/Kayseri_%C3%9Cniversitesi_logo.png",
    "Kıbrıs İlim Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/2/2d/Cyprus_Aydin_University_Front_Door.jpg",
    "Kırıkkale Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/f/f4/K%C4%B1r%C4%B1kkale_%C3%BCniversitesi_yeni_logosu.jpeg",
    "Kırklareli Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/e/e7/K%C4%B1rklareli_%C3%9Cniversitesi_logosu.jpg",
    "Kilis 7 Aralık Üniversitesi": "https://ui-avatars.com/api/?name=Kilis+7+Aral%C4%B1k+%C3%9Cniversitesi&background=random",
    "Kocaeli Sağlık ve Teknoloji Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/7/74/Kost%C3%BC_logo.png",
    "Kocaeli Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/1/1a/Kouyenilogo.png",
    "Koç Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/9/9d/Ko%C3%A7_Universitesi.jpg",
    "Konya Teknik Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Konya_Teknik_%C3%9Cniversitesi_logo.svg/1280px-Konya_Teknik_%C3%9Cniversitesi_logo.svg.png",
    "Kütahya Dumlupınar Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/thumb/b/b5/K%C3%BCtahya_Dumlup%C4%B1nar_%C3%9Cniversitesi_logo.png/1280px-K%C3%BCtahya_Dumlup%C4%B1nar_%C3%9Cniversitesi_logo.png",
    "Kütahya Sağlık Bilimleri Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/1/1f/K%C3%BCtahya_Sa%C4%9Fl%C4%B1k_Bilimleri_%C3%9Cniversitesi_logo.png",
    "Lokman Hekim Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Lokman_Hekim_%C3%9Cniversitesi_logo.svg/1280px-Lokman_Hekim_%C3%9Cniversitesi_logo.svg.png",
    "Malatya Turgut Özal Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Malatya_Turgut_%C3%96zal_%C3%9Cniversitesi_logo.svg/1280px-Malatya_Turgut_%C3%96zal_%C3%9Cniversitesi_logo.svg.png",
    "Maltepe Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/f/f9/Maltepe_%C3%9Cniversitesi_logo.png",
    "Manisa Celal Bayar Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/f/f3/Celal_bayar_%C3%BCniversitesi_yeni_logosu.png",
    "Mardin Artuklu Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Mardin_Artuklu_University_logo.svg/1280px-Mardin_Artuklu_University_logo.svg.png",
    "Marmara Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/7/70/Marmara_%C3%9Cniversitesi_logo.png",
    "MEF Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/0/0a/Mef_Universitesi_Logo.jpg",
    "Mersin Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Mersin_University_logo.svg/1280px-Mersin_University_logo.svg.png",
    "Mudanya Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/8/89/Mudanya_%C3%9Cniversitesi.png",
    "Muğla Sıtkı Koçman Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Mu%C4%9Fla_S%C4%B1tk%C4%B1_Ko%C3%A7man_University_logo.svg/960px-Mu%C4%9Fla_S%C4%B1tk%C4%B1_Ko%C3%A7man_University_logo.svg.png",
    "Munzur Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Munzur_University_logo.svg/1280px-Munzur_University_logo.svg.png",
    "Muş Alparslan Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Mu%C5%9F_Alparslan_%C3%9Cniversitesi_logo.svg/1280px-Mu%C5%9F_Alparslan_%C3%9Cniversitesi_logo.svg.png",
    "Necmettin Erbakan Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/7/79/Necmettin_Erbakan_%C3%9Cniversitesi_logosu.png",
    "Nevşehir Hacı Bektaş Veli Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/c/c9/Nev%C5%9Fehir_%C3%9Cniversitesi_logo.png",
    "Niğde Ömer Halisdemir Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Ni%C4%9Fde_%C3%96mer_Halisdemir_University_logo.svg/1280px-Ni%C4%9Fde_%C3%96mer_Halisdemir_University_logo.svg.png",
    "Nişantaşı Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Mavi.png/1280px-Mavi.png",
    "Nuh Naci Yazgan Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/7/72/Nuh_Naci_Yazgan_%C3%9Cniversitesi_logosu.jpg",
    "Ondokuz Mayıs Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/thumb/c/c4/OM%C3%9C_logo.svg/1280px-OM%C3%9C_logo.svg.png",
    "Orta Doğu Teknik Üniversitesi (ODTÜ)": "https://upload.wikimedia.org/wikipedia/commons/2/2f/Logo_of_METU.svg",
    "Osmaniye Korkut Ata Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/8/84/Osmaniye_Korkut_Ata_%C3%9Cniversitesi.jpg",
    "Ostim Teknik Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/b/b7/Ostim_Teknik_%C3%9Cniversitesi_Logosu.png",
    "Özyeğin Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/%C3%96zye%C4%9Fin_University_Campus.jpg/1280px-%C3%96zye%C4%9Fin_University_Campus.jpg",
    "Pamukkale Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Pamukkale_University_logo.svg/1280px-Pamukkale_University_logo.svg.png",
    "Piri Reis Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/c/cf/PiriReisUniversitesiLogo.png",
    "Recep Tayyip Erdoğan Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/3/32/Recep_Tayyip_Erdo%C4%9Fan_%C3%9Cniversitesi.png",
    "Sabancı Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Sabanc%C4%B1_%C3%9Cniversitesi_Giri%C5%9F.jpg/1280px-Sabanc%C4%B1_%C3%9Cniversitesi_Giri%C5%9F.jpg",
    "Sağlık Bilimleri Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/0/06/SB%C3%9C_logo.png",
    "Sakarya Uygulamalı Bilimler Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Sakarya_University_of_Applied_Sciences_logo.svg/1280px-Sakarya_University_of_Applied_Sciences_logo.svg.png",
    "Sakarya Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Sakarya_University_logo.svg/960px-Sakarya_University_logo.svg.png",
    "Samsun Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/c/c6/Samsun_%C3%9Cniversitesi_logo.png",
    "Sanko Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Sanko_%C3%9Cniversitesi_logo.svg/960px-Sanko_%C3%9Cniversitesi_logo.svg.png",
    "Selçuk Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/f/f5/Sel%C3%A7uk_%C3%9Cniversitesi_logosu.png",
    "Siirt Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/e/e3/Siirt_%C3%BCniversitesi.png",
    "Sinop Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/7/72/Sinop_Universitesi_Logo.png",
    "Sivas Bilim ve Teknoloji Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/4/4c/Sivas_Bilim_ve_Teknoloji_%C3%9Cniversitesi_logosu.png",
    "Sivas Cumhuriyet Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/4/45/SivasCumhuriyet%C3%9CniLogo.png",
    "Süleyman Demirel Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/e/e5/S%C3%BCleyman_Demirel_%C3%9Cniversitesi_logosu.png",
    "Şırnak Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/b/b8/%C5%9E%C4%B1rnak_%C3%9Cniversitesi_logosu.jpg",
    "Tarsus Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Tarsus_%C3%9Cniversitesi_logo.svg/1280px-Tarsus_%C3%9Cniversitesi_logo.svg.png",
    "TED Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/8/89/TED_%C3%9Cniversitesi_logosu.png",
    "TOBB Ekonomi ve Teknoloji Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/4/4d/TOBB_ET%C3%9C_logo.png",
    "Tokat Gaziosmanpaşa Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/0/09/GO%C3%9C_20._y%C4%B1l_logo.png",
    "Toros Üniversitesi": "https://ui-avatars.com/api/?name=Toros+%C3%9Cniversitesi&background=random",
    "Trabzon Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/8/89/Trabzon_%C3%9Cniversitesi.png",
    "Trakya Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/1/14/Trakya_%C3%9Cniversitesi_logosu.jpg",
    "Türk Hava Kurumu Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/4/4f/T%C3%BCrk_Hava_Kurumu_%C3%9Cniversitesi_logo.png",
    "Türk-Alman Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/f/f4/Logo_T%C3%BCrk_Alman_%C3%9Cniversitesi.jpg",
    "Ufuk Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/9/90/Ufuk_%C3%9Cniversitesi_Yeni_Logo.png",
    "Uşak Üniversitesi": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/U%C5%9Fak_University_logo.svg/1280px-U%C5%9Fak_University_logo.svg.png",
    "Üsküdar Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/b/ba/%C3%9Csk%C3%BCdar_%C3%9Cniversitesi_logo.png",
    "Van Yüzüncü Yıl Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/7/77/Y%C3%BCz%C3%BCnc%C3%BC_Y%C4%B1l_%C3%9Cniversitesi_logo.png",
    "Yalova Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/8/86/Yalova_%C3%9Cniversitesi_logosu.jpg",
    "Yeditepe Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/2/28/Yeditepe_%C3%9Cniversitesi_logo.png",
    "Yozgat Bozok Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/8/87/Yozgatbozokuni_logo.jpg",
    "Yüksek İhtisas Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/3/34/Yuksek_ihtisas_universitesi.png",
    "Zonguldak Bülent Ecevit Üniversitesi": "https://upload.wikimedia.org/wikipedia/tr/9/92/B%C3%BClent_Ecevit_%C3%9Cniversitesi_logo.png"
};
